#!/bin/sh
bspc monitor -d "I" "II" "III" "IV"
bspc config focus_follows_pointer true
bspc config window_gap 6
bspc config automatic_scheme alternate
bspc config focused_border_color \#454545
bspc config normal_border_color \#282828
