#!/bin/sh

# Source init script
source ~/.dotfiles/scripts/init/init.sh

# bspwm config
## Monitors
bspc monitor $MONITOR -d 1 2 3 4 5

## Rules
bspc rule -a Zathura state=tiled

## Other
bspc config focus_follows_pointer true
bspc config window_gap 10
