#!/bin/sh
export TERMINAL="urxvt"

KEYBOARD_DELAY=200
KEYBOARD_RATE=25
MOUSE_ACCEL=-0.75
MOUSE_DEVID=9

feh --bg-scale --no-fehbg ~/.dotfiles/.wallpaper.jpg

# Run background tasks
killall -q sxhkd; sxhkd &
killall -q picom; sleep 0.3s; picom &
killall -q polybar; polybar mainbar-bspwm &
killall -q ckb-next; ckb-next -b &

# Mouse speed
xinput --set-prop $MOUSE_DEVID 'libinput Accel Speed' $MOUSE_ACCEL

# Keyboard speed
xset r rate $KEYBOARD_DELAY $KEYBOARD_RATE

# bspwm config
## Monitors
bspc monitor HDMI-0 -d 1 2 3 4 5

## Other
bspc config focus_follows_pointer true
bspc config window_gap 10
bspc config top_padding 20

